project:
  type: website
  output-dir: .

website:
  title: "Yandi Andiyana"
  navbar:
    background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Articles"
        href: articles.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Courses"
        href: courses.qmd
format:
  html:
    theme: flatly
    css: styles.css
