project:
  type: website
  output-dir: .

website:
  title: "Yandi Andiyana S.Si., M.Si."
  navbar:
    background: light
    left:
      - text: "Assalamu'alaikum"
        href: index.qmd
        id: "home-link"
      - text: "Tulisan & Bacaan"
        href: articles.qmd
      - text: "Karya & Kerjasama"
        href: projects.qmd
      - text: "Kelas & Konsultasi"
        href: courses.qmd
format:
  html:
    theme: cosmo
    css: styles.css
