project:
  type: website
  output-dir: _site

website:
  title: "Yandi Andiyana, S.Si., M.Si."
  navbar:
    background: light
    left:
      - text: "السلام عليكم"
        href: index.qmd
        id: home-link
      - text: "Blog"
        href: blog/index.qmd
      - text: "Courses"
        href: courses.qmd
      - text: "Projects"
        href: projects.qmd
format:
  html:
    theme: cosmo
    css: styles.css
