project:
  type: website
  output-dir: .

website:
  title: "Yandi Andiyana, S.Si., M.Si."
  navbar:
    background: light
    left:
      - text: "السلام عليكم"
        href: index.qmd
        id: home-link
      - text: "Projects"
        href: projects.qmd
      - text: "Classes"
        href: classes.qmd
      - text: "Collaborations"
        href: collaborations.qmd
format:
  html:
    theme: cosmo
    css: styles.css
