project:
  type: website
  output-dir: .

website:
  title: "Yandi Andiyana, S.Si., M.Si."
  navbar:
    background: light
    left:
      - text: "السلام عليكم"
        href: index.qmd
      - text: "Tulisan & Bacaan"
        href: articles.qmd
      - text: "Karya & Kerja Sama"
        href: projects.qmd
      - text: "Kelas & Konsultasi"
        href: courses.qmd
format:
  html:
    theme: cosmo
    css: styles.css
